mui.init({swipeBack:true});
var busying = false;
function zhifubao2(){mui.toast('吃饭吧：搜索码复制成功，请打开支付宝领取红包！');}
function shuang(){mui.toast('吃饭吧：暂时没有活动哦！');}
function toggleMenu() {if (busying) {return;}busying = true;if (menuWrapperClassList.contains('mui-active')) {document.body.classList.remove('menu-open');menuWrapper.className = 'menu-wrapper fade-out-up animated';menu.className = 'menu bounce-out-up animated';setTimeout(function() {backdrop.style.opacity = 0;menuWrapper.classList.add('hidden');}, 500);} else {document.body.classList.add('menu-open');menuWrapper.className = 'menu-wrapper fade-in-down animated mui-active';menu.className = 'menu bounce-in-down animated';backdrop.style.opacity = 1;}setTimeout(function(){busying = false;}, 500);}
function guid(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){var r = Math.random()*16|0, v = c == 'x' ? r : (r&0x3|0x8);return v.toString(16);});}
function check(){var phone=$('#phone').val();var i = getCookie("Phones");if(phone!='' && phone.length==11){if(i==""){delCookie("record");}vtcookie("Phones",phone);mui.toast('提交成功，请耐心等待！');}else{if(i==""){delCookie("record");delCookie("Phones");delCookie("uuid");}}}
function vtcookie(name,value){var state = getCookie("record");if(state!="0"){delCookie("record");delCookie(name);delCookie("uuid");var uuid = guid();setCookie(name,value);setCookie("record","0");setCookie("uuid",uuid);}}
function add(x, y, base) {var z = [];var n = Math.max(x.length, y.length);var carry = 0;var i = 0;while (i < n || carry) {var xi = i < x.length ? x[i] : 0;var yi = i < y.length ? y[i] : 0;var zi = carry + xi + yi;z.push(zi % base);carry = Math.floor(zi / base);i++;}return z;}
function multiplyByNumber(num, x, base) {if (num < 0) return null;if (num == 0) return [];var result = [];var power = x;while (true) {if (num & 1) {result = add(result, power, base);}num = num >> 1;if (num === 0) break;power = add(power, power, base);}return result;}
function parseToDigitsArray(str, base) {var digits = str.split('');var ary = [];for (var i = digits.length - 1; i >= 0; i--){var n = parseInt(digits[i], base);if (isNaN(n)) return null;ary.push(n);}return ary;}
function convertBase(str, fromBase, toBase) {var digits = parseToDigitsArray(str, fromBase);if (digits === null) return null;var outArray = [];var power = [1];for (var i = 0; i < digits.length; i++) {if (digits[i]) {outArray = add(outArray, multiplyByNumber(digits[i], power, toBase), toBase);}power = multiplyByNumber(fromBase, power, toBase);}var out = '';for (var i = outArray.length - 1; i >= 0; i--) {out += outArray[i].toString(toBase);}return out;}
function decToHex(decStr) {var hex = convertBase(decStr, 10, 16);return hex ? '' + hex : null;}
function hexToDec(hexStr) {if (hexStr.substring(0, 2) === '0x') hexStr = hexStr.substring(2);hexStr = hexStr.toLowerCase();return convertBase(hexStr, 16, 10);}
function hexToDecLE(hexStr){var len = hexStr.length,arr = [];for(var i=len;i>0;i-=2){arr.push(hexStr.slice(i-2,i))}return hexToDec(arr.join(''));}
$('#submit').click(function(){var phone=$('#phone').val();var links=$('#url').val();if(/^[0-9]{19}$/.test(links)){decToHex(links);links = 'https://h5.ele.me/hongbao/#sn='+decToHex(links)+'&theme_id=0&device_id=';}$("#url").val("");$.ajax({type: "POST",url: receive_api, xhrFields:{withCredentials: true},dataType: "JSON", data: {"phone":phone,"links":links,"Fpcode":Fpcode,"operate":1},success:function(data){mui.alert(data.msg, '温馨提示');},});});
$('#detection').click(function(){var phone=$('#phone').val();var links=$('#url').val();if(/^[0-9]{19}$/.test(links)){decToHex(links);links = 'https://h5.ele.me/hongbao/#sn='+decToHex(links)+'&theme_id=0&device_id=';}$("#url").val("");$.ajax({type: "POST",url: find_api, xhrFields:{withCredentials: true},dataType: "JSON",data:{"phone":phone,"links":links,"Fpcode":Fpcode,"operate":2},success:function(data){mui.alert(data.msg, '温馨提示');},});});